### ISSUE TITLE
Get Navigation as mainpage

### ISSUE THREAD

**Issue by wbmarkus** [Siphalor/mkdocs-custommill#1]
I gave custommill a try. However, I am getting just the navigation as mainpage and cannot see the actual content. Windmill works fine.
![image](https://user-images.githubusercontent.com/87238631/128321176-0c2fa663-17ff-4850-8c26-3ce5226015a9.png)

**Comment by Siphalor** [comment]
Hey, thanks for giving this a try :)

Have you set the `theme.home` variable in the `mkdocs.yml` file?
For this theme it is necessary that you explicitly set the home page, as mkdocs-custommill brings it's own index.html file.

**Comment by wbmarkus** [comment]
These are the entries in the yaml config file:
```  
theme:
  name: custommill
  home: index
  search_index_only: true
  include_search_page: true
  locale: en
  highlightjs: true

nav:
  - Home: index.md
  - Set up documentation: techdoc_setup.md
  - Writing Documentation:
    - Style guide: styleguide.md
    - Formatting: formatting_rules.md
  - Kickstart: kickstart_template.md
  - Why only English: why_only_english.md
  - Glossary: wb_glossary.md
```

**Comment by Siphalor** [comment]
ah, I see.

Since CustomMill generates it's own `index.html` it'll conflict with your `index.md`.
You shouldn't call your landing page `index.md` for this theme but something else like `home.md` and go with that.

The docs currently don't really explain that well, so I'm gonna see if I can clarify it a bit.

**Comment by Siphalor** [comment]
Did that solve the issue?

**Comment by wbmarkus** [comment]
Hi,

It did solve the issue. However, the fact that users cannot name their main page index.md is an issue so custommill is not an option.

Thanks for your help.
Markus

Markus Barth
Technical Documentation

WebBeds
Calle Calçat 6, Polígono Son Valentí
07011 Palma de Mallorca, Spain
W  webbeds.com<http://www.webbeds.com/>
***@***.***

**Comment by SIGSTACKFAULT** [comment]
Just spent 30 minutes on this problem. maybe it should be in the README or something
